services:
  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server"]
    restart: always

  postgres:
    image: postgres:16.4
    restart: always
    ports:
      - "5432:5432"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db